"""
db/session_repository.py — MongoDB CRUD layer for AI-agent session documents.

All public methods are async and use Motor (non-blocking).

Document schema
---------------
{
    "session_id":        str,           # unique, generated by the agent
    "parent_session_id": str | None,    # set when resuming a prior session
    "user_id":           str,
    "app_id":            str,           # "ai_interviewer" | "code_reviewer" | "roadmap_generator"

    "input":             dict,          # agent-specific raw input

    "pipeline":          dict,          # keyed by step name; each value is a StepResult dict
    "optional_steps":    dict,          # keyed by step name; e.g. "optimize", "chat_refine"

    "final_response":    dict | None,

    "status":            str,           # "in_progress" | "completed" | "failed"

    "created_at":        datetime (UTC)
    "updated_at":        datetime (UTC)
    "last_activity_at":  datetime (UTC)
}

Usage
-----
    from db.session_repository import session_repository

    await session_repository.create_session({ ... })
    await session_repository.update_session_step(sid, "pipeline.technical_review", output)
    await session_repository.complete_session(sid, final_response={...})
"""

import logging
from datetime import datetime, timezone
from typing import Any

from pymongo import ReturnDocument
from pymongo.errors import DuplicateKeyError

from .mongo import get_db

log = logging.getLogger("db.session_repository")


def _now() -> datetime:
    return datetime.now(timezone.utc)


class SessionRepository:
    """
    Thin async wrapper around the MongoDB ``sessions`` collection.

    All methods catch driver-level exceptions, log them, and re-raise so that
    the calling agent can decide how to handle persistence failures without
    silently swallowing errors.
    """

    # ── Collection accessor ───────────────────────────────────────────────────

    @property
    def _col(self):
        return get_db()["sessions"]

    # ── Create ────────────────────────────────────────────────────────────────

    async def create_session(self, data: dict) -> dict:
        """
        Insert a new session document.

        ``data`` must contain at minimum:
            - session_id  (str, unique)
            - user_id     (str)
            - app_id      (str)
            - input       (dict)

        Timestamps are injected automatically; ``status`` defaults to
        ``"in_progress"`` when not supplied.

        Returns the inserted document.

        Raises DuplicateKeyError if session_id already exists.
        """
        now = _now()
        doc = {
            "parent_session_id": None,
            "pipeline":          {},
            "optional_steps":    {},
            "final_response":    None,
            "status":            "in_progress",
            **data,               # caller values override defaults above
            "created_at":        now,
            "updated_at":        now,
            "last_activity_at":  now,
        }

        try:
            await self._col.insert_one(doc)
            log.info(
                "Session created  session_id=%s  user_id=%s  app_id=%s",
                doc["session_id"], doc.get("user_id"), doc.get("app_id"),
            )
            return doc
        except DuplicateKeyError:
            log.error("Duplicate session_id: %s", data.get("session_id"))
            raise

    # ── Step-level update ─────────────────────────────────────────────────────

    async def update_session_step(
        self,
        session_id: str,
        field_path: str,
        value: Any,
    ) -> dict | None:
        """
        Write the output of a single pipeline step into the session document.

        ``field_path`` uses dot-notation to target nested fields:
            "pipeline.code_understanding"
            "pipeline.technical_review"
            "optional_steps.optimize"
            "optional_steps.chat_refine"

        The ``updated_at`` and ``last_activity_at`` timestamps are refreshed
        automatically on every call.

        Returns the updated document, or None if no document was matched.

        Example
        -------
            await session_repository.update_session_step(
                session_id,
                "pipeline.technical_review",
                {
                    "model": "claude-opus",
                    "output": { ... },
                    "timestamp": datetime.now(timezone.utc).isoformat(),
                }
            )
        """
        now = _now()
        result = await self._col.find_one_and_update(
            {"session_id": session_id},
            {
                "$set": {
                    field_path:         value,
                    "updated_at":       now,
                    "last_activity_at": now,
                }
            },
            return_document=ReturnDocument.AFTER,
        )

        if result is None:
            log.warning(
                "update_session_step: session not found  session_id=%s  field=%s",
                session_id, field_path,
            )
        else:
            log.debug(
                "Session step saved  session_id=%s  field=%s",
                session_id, field_path,
            )

        return result

    # ── Complete ──────────────────────────────────────────────────────────────

    async def complete_session(
        self,
        session_id: str,
        final_response: dict,
        status: str = "completed",
    ) -> dict | None:
        """
        Mark the session as finished and persist the final agent output.

        ``status`` should be ``"completed"`` (success) or ``"failed"`` (error).

        Returns the updated document, or None if no document was matched.

        Example
        -------
            await session_repository.complete_session(
                session_id,
                final_response={
                    "summary":    "Code reviewed and optimised",
                    "final_code": "class LRUCache: ...",
                    "highlights": ["Fixed bug for capacity=0"],
                },
                status="completed",
            )
        """
        now = _now()
        result = await self._col.find_one_and_update(
            {"session_id": session_id},
            {
                "$set": {
                    "final_response":  final_response,
                    "status":          status,
                    "updated_at":      now,
                    "last_activity_at": now,
                }
            },
            return_document=ReturnDocument.AFTER,
        )

        if result is None:
            log.warning(
                "complete_session: session not found  session_id=%s", session_id
            )
        else:
            log.info(
                "Session %s  session_id=%s  user_id=%s  app_id=%s",
                status, session_id,
                result.get("user_id"), result.get("app_id"),
            )

        return result

    # ── Read helpers ──────────────────────────────────────────────────────────

    async def get_session_by_id(self, session_id: str) -> dict | None:
        """
        Fetch a single session document by its ``session_id``.

        Returns the document dict, or None if not found.
        """
        return await self._col.find_one(
            {"session_id": session_id},
            {"_id": 0},   # suppress internal ObjectId from callers
        )

    async def get_active_session(
        self,
        user_id: str,
        app_id: str,
    ) -> dict | None:
        """
        Return the most-recent ``in_progress`` session for the given
        user + app combination, or None if no such session exists.

        Used by the resume logic before creating a new session:

            existing = await session_repository.get_active_session(user_id, app_id)
            if existing:
                session_id = existing["session_id"]  # resume
            else:
                session_id = generate_new_id()       # start fresh
        """
        return await self._col.find_one(
            {
                "user_id": user_id,
                "app_id":  app_id,
                "status":  "in_progress",
            },
            {"_id": 0},
            sort=[("created_at", -1)],   # most recent first
        )

    async def get_sessions_by_user(
        self,
        user_id: str,
        app_id: str | None = None,
        limit: int = 20,
    ) -> list[dict]:
        """
        Retrieve a paginated list of sessions for a user, newest first.

        Optionally filter by ``app_id``.
        """
        query: dict = {"user_id": user_id}
        if app_id:
            query["app_id"] = app_id

        cursor = (
            self._col
            .find(query, {"_id": 0})
            .sort("created_at", -1)
            .limit(limit)
        )
        return await cursor.to_list(length=limit)

    # ── Failure helper ────────────────────────────────────────────────────────

    async def fail_session(
        self,
        session_id: str,
        reason: str = "unexpected error",
    ) -> dict | None:
        """
        Convenience wrapper: mark a session as ``"failed"`` with an error note.

        Call this inside ``except`` blocks so interrupted sessions are not left
        perpetually ``"in_progress"`` (which would block the resume logic).
        """
        return await self.complete_session(
            session_id,
            final_response={"error": reason},
            status="failed",
        )


# ── Module-level singleton ────────────────────────────────────────────────────

session_repository = SessionRepository()